# Generated by Django 6.0.1 on 2026-02-09 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LFGPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('game_mode', models.CharField(choices=[('RANKED_SOLO', 'Ranked Solo/Duo'), ('RANKED_FLEX', 'Ranked Flex'), ('NORMAL', 'Normal Blind/Draft'), ('ARAM', 'ARAM'), ('CLASH', 'Clash')], default='RANKED_SOLO', max_length=20)),
                ('region', models.CharField(choices=[('BR', 'Brazil'), ('EUNE', 'Europe Nordic & East'), ('EUW', 'Europe West'), ('LAN', 'Latin America North'), ('LAS', 'Latin America South'), ('NA', 'North America'), ('OCE', 'Oceania'), ('RU', 'Russia'), ('TR', 'Turkey'), ('ME', 'Middle East'), ('JP', 'Japan'), ('KR', 'Republic of Korea'), ('SEA', 'Southeast Asia'), ('TW', 'Taiwan, Hong Kong, Macao'), ('VN', 'Vietnam'), ('PBE', 'Public Beta Environment')], default='EUW', max_length=30)),
                ('host_tier', models.CharField(choices=[('UNRANKED', 'Unranked'), ('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('CHALLENGER', 'Challenger')], default='UNRANKED', max_length=20)),
                ('min_tier', models.CharField(choices=[('UNRANKED', 'Unranked'), ('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('CHALLENGER', 'Challenger')], default='UNRANKED', max_length=20)),
                ('host_role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('FILL', 'Fill')], default='FILL', max_length=20)),
                ('looking_for_role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('FILL', 'Fill')], default='FILL', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.lfgpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('discord_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('game_name', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=10, null=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('puuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('icon_id', models.IntegerField(blank=True, default=29, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
