# Generated by Django 6.0.1 on 2026-02-03 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LFGPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('game_mode', models.CharField(choices=[('RANKED_SOLO', 'Ranked Solo/Duo'), ('RANKED_FLEX', 'Ranked Flex'), ('NORMAL', 'Normal Blind/Draft'), ('ARAM', 'ARAM'), ('CLASH', 'Clash')], default='RANKED_SOLO', max_length=20)),
                ('host_rank', models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master+'), ('UNRANKED', 'Unranked')], default='UNRANKED', max_length=20)),
                ('min_rank', models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master+'), ('UNRANKED', 'Unranked')], default='UNRANKED', max_length=20)),
                ('host_role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('FILL', 'Fill')], default='FILL', max_length=20)),
                ('looking_for_role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('FILL', 'Fill')], default='FILL', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lfgpost')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('riot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discord_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
