# Generated by Django 6.0.1 on 2026-02-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lfgpost',
            old_name='rank',
            new_name='host_rank',
        ),
        migrations.AddField(
            model_name='lfgpost',
            name='host_role',
            field=models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('FILL', 'Fill')], default='FILL', max_length=20),
        ),
        migrations.AddField(
            model_name='lfgpost',
            name='min_rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master+'), ('UNRANKED', 'Unranked')], default='<django.db.models.fields.CharField>', max_length=20),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='looking_for_role',
            field=models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('FILL', 'Fill')], default='FILL', max_length=20),
        ),
    ]
