# Generated by Django 6.0.1 on 2026-02-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_lfgpost_host_rank_remove_lfgpost_min_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='region',
            field=models.CharField(choices=[('BR', 'Brazil'), ('EUNE', 'Europe Nordic & East'), ('EUW', 'Europe West'), ('LAN', 'Latin America North'), ('LAS', 'Latin America South'), ('NA', 'North America'), ('OCE', 'Oceania'), ('RU', 'Russia'), ('TR', 'Turkey'), ('ME', 'Middle East'), ('JP', 'Japan'), ('KR', 'Republic of Korea'), ('SEA', 'Southeast Asia'), ('TW', 'Taiwan, Hong Kong, Macao'), ('VN', 'Vietnam'), ('PBE', 'Public Beta Environment')], default='EUW', max_length=30),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='host_tier',
            field=models.CharField(choices=[('UNRANKED', 'Unranked'), ('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('CHALLENGER', 'Challenger')], default='UNRANKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='min_tier',
            field=models.CharField(choices=[('UNRANKED', 'Unranked'), ('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('CHALLENGER', 'Challenger')], default='UNRANKED', max_length=20),
        ),
    ]
