# Generated by Django 6.0.1 on 2026-02-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_rank_lfgpost_host_rank_lfgpost_host_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfgpost',
            name='min_rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master+'), ('UNRANKED', 'Unranked')], default='UNRANKED', max_length=20),
        ),
    ]
