# Generated by Django 6.0.1 on 2026-02-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_lfgpost_min_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfgpost',
            name='min_rank',
        ),
    ]
